### PR TITLE
feat: add load method

### PR DESCRIPTION
**Pull request by WoLewicki**
## PR concerning New Architecture support in the library :tada:

We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)

or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)

---

## Summary

PR adding `load` method needed for dynamic frameworks to work with the library. See https://github.com/facebook/react-native/pull/37274 for more information.

### CODE REVIEW

**Comment by kirillzyusko** [comment]
Oh, I knew it would hit me at some point of time 🙃 

It was in my ToDo list, to check how the library works with dynamic frameworks. I haven't digged into all internals, but may I ask you how to test these changes? Just add `use_frameworks` to Podfile? Without this line the compilation will fail or it will be a runtime error?

Sorry if questions sound stupid, just thinking whether it's worth to add checks to CI somehow 👀

**Comment by kirillzyusko** [comment]
Do not pay an attention to failing CI job - it's just because you are external contributor and I still haven't figured out how to fix them for external contributions 😅

**Comment by kirillzyusko** [comment]
Anyway, I think it's a great addition and I don't want to stop this PR from being merged just because of the questions!

Changes look good to me! Thank you for contribution!

**Comment by WoLewicki** [comment]
> I haven't digged into all internals, but may I ask you how to test these changes? Just add use_frameworks to Podfile? Without this line the compilation will fail or it will be a runtime error?

You should specify `ENV['USE_FRAMEWORKS'] = 'dynamic'` in your app's `Podfile`. If you compile it without my code, the interop layer will be used instead of the fabric code you added for this component. I think you should see it by adding breakpoint in `initWithFrame` method and see that it is not called then.

**Pull request merged**
