### PR TITLE
chore: react-native 0.72 support

### PR DESCRIPTION
**Pull request by kirillzyusko**
## 📜 Description

Updated `react-native` and related packages to its latest published versions.

## 💡 Motivation and Context

To be ready for new upcoming changes we need to regularly update packages and be aligned with `react-native`. Sometimes new packages may require changes to make it working as it worked before 🙂 

Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/196

## 🔮 Known issues

- Android, Fabric, KeyboardAwareScrollView -> `scrollTo` from REA doesn't work as expected.
- Chat works slowly on Android (especially < 11) - will be handled in separate PR.

### JS
- react-native 0.72;
- lottie example in Fabric app;
- reanimated 3.4.2 everywhere;
- unit tests in fabric app;
- react-native-gesture-handler is not complaining about packages duplicate in example/FabricExample;

## 🤔 How Has This Been Tested?

Tested on:
- Xiaomi Redmi Note 5 Pro (Android 9);
- Pixel 7 Pro (Android 13);
- iPhone 14 Pro (iOS 16.4, simulator);
- iPhone 14 Pro (iOS 16.5.1, real device);
- iPhone 6s (iOS 15.6, real device).

## 📝 Checklist

- [x] CI successfully passed

### CODE REVIEW

**Comment by NguyenHoangMinhkkkk** [comment]
hi, i'm working on new project and using newest anything form RN to Libs.
"react-native": "0.72.3" 
"react-native-reanimated": "^3.4.0"

That a lot of works to do for you guys. hope to see the update soon. thank you! great job!

**Comment by kirillzyusko** [comment]
Hi @NguyenHoangMinhkkkk 
This library doesn't require any code changes for RN 0.72 compatibility. You can use `1.5.8` version with RN 0.72 and it'll work 🙂

**Comment by NguyenHoangMinhkkkk** [comment]
> 

hi i just started to try implement the KeyboardAwareScrollView copied from /example project and it not yet working both android/ios. i will double check again. 
do you think it not works because rn-reanimated 3.4.0 or something?

**Comment by kirillzyusko** [comment]
@NguyenHoangMinhkkkk from my observation KeyboardAwareScrollView doesn't work in this PR in Fabric/Android (I was tested REA 3.3.0, on REA 3.4.0 I can not run example project at all, but I haven't checked why yet).

Also, please notice, that current `main` branch contains some changes that are not published to `npm` yet. For example upcoming `1.6.0` will give `tag` value in event - however now it's not available in `1.5.8` which is current version on `npm`. So if you are trying to run `KeyboardAwareScrollView` from `main` branch using `1.5.8` version - most likely it will not work. You'll need to check `1.5.8` tag and copy code from this version.

**Pull request merged**
